FROM registry.aliyuncs.com/nbg/centos-nginx110-php56:0.19
MAINTAINER sobeyservice@sobey.com
 
RUN mkdir -p /sobey/H5creditshop
ADD / /sobey/H5creditshop/

ADD dockerfile/cctv5/jifen.conf /etc/nginx/conf.d/
